%% ============================================================
% POPULATION-AVERAGE ACTUAL VERSUS PREDICTED
%
% Fits three divisive-gain models using contiguous temporal
% cross-validation and plots held-out population-average predictions.
%
% Each panel contains:
%   1. Density of actual-versus-predicted observations
%   2. Identity line
%   3. Least-squares fitted line
%   4. Fitted slope as the panel title
%
% Panels 1 and 2 also contain the inhibitory-scale comparison line.
%% ============================================================

% clear;
% clc;
% close all;

%% ------------------------------------------------------------
% Data location and analysis settings
%% ------------------------------------------------------------

PreRun_Data=0; %0 For Newly Simulated Data

if PreRun_Data==1
data_dir = [ ...
    '/Users/josehurtado/Documents/MATLAB/Final_Manuscript/' ...
    'Random_EIPlaceNet_Data/Supplementary/' ...
    'S04/Conductance_Model/PreRun_Data/Fast_Pos/'];
data_file = fullfile(data_dir, 'ConductanceModel_Data.mat');
end

n_time_folds = 50;
fit_downsample = 1000;

tiny = 1e-12;
optimizer_tolerance = 1e-10;

beta_lower_bound = 1e-8;
beta_upper_bound = 1e4;

%% ------------------------------------------------------------
% Load only the variables required for fitting and plotting
%% ------------------------------------------------------------
if PreRun_Data==1
D = load( ...
    data_file, ...
    'total_time_vec', ...
    'VmE', ...
    'VmE_pre', ...
    'INetE', ...
    'gInputE_history', ...
    'gInhE');

total_time_vec = double(D.total_time_vec(:).');

VmE = double(D.VmE);
VmE_pre = double(D.VmE_pre);
INetE = double(D.INetE);

gInputE_history = double(D.gInputE_history);
gInhE = double(D.gInhE);

clear D
end
%% ------------------------------------------------------------
% Orient matrices as neurons x time
%% ------------------------------------------------------------

n_time = numel(total_time_vec);

VmE = orient_cells_by_time(VmE, n_time, 'VmE');
VmE_pre = orient_cells_by_time(VmE_pre, n_time, 'VmE_pre');
INetE = orient_cells_by_time(INetE, n_time, 'INetE');

gInputE_history = orient_cells_by_time( ...
    gInputE_history, n_time, 'gInputE_history');

gInhE = orient_cells_by_time( ...
    gInhE, n_time, 'gInhE');

if ~isequal(size(VmE), size(VmE_pre), size(INetE), ...
        size(gInputE_history), size(gInhE))

    error('All neuron-by-time matrices must have identical dimensions.');
end

if any(~isfinite(VmE), 'all') || ...
        any(~isfinite(VmE_pre), 'all') || ...
        any(~isfinite(INetE), 'all') || ...
        any(~isfinite(gInputE_history), 'all') || ...
        any(~isfinite(gInhE), 'all')

    error('The required input matrices contain nonfinite values.');
end

% Preserve the original handling of tiny negative conductance values.
input_negative_tolerance = ...
    1e-12 * max(1, max(abs(gInputE_history), [], 'all'));

if any(gInputE_history(:) < -input_negative_tolerance)
    error('gInputE_history contains materially negative values.');
end

gInputE_history(gInputE_history < 0) = 0;

inh_negative_tolerance = ...
    1e-12 * max(1, max(abs(gInhE), [], 'all'));

if any(gInhE(:) < -inh_negative_tolerance)
    error('gInhE contains materially negative values.');
end

gInhE(gInhE < 0) = 0;

%% ------------------------------------------------------------
% Observed response
%% ------------------------------------------------------------

deltaVmE = VmE - VmE_pre;

population_observed_deltaVmE = ...
    mean(deltaVmE, 1);

%% ------------------------------------------------------------
% Construct contiguous temporal cross-validation folds
%% ------------------------------------------------------------

if n_time_folds < 2 || n_time_folds > n_time
    error('n_time_folds must be between 2 and the number of samples.');
end

time_fold_id = ...
    ceil((1:n_time) .* n_time_folds ./ n_time);

time_fold_id = ...
    min(max(time_fold_id, 1), n_time_folds);

%% ------------------------------------------------------------
% Allocate held-out population-average predictions
%% ------------------------------------------------------------

CV_fixed_gain_prediction = nan(1, n_time);
CV_input_gain_prediction = nan(1, n_time);
CV_inhibitory_gain_prediction = nan(1, n_time);

CV_fixed_at_inhibitory_scale_prediction = nan(1, n_time);
CV_input_at_inhibitory_beta_prediction = nan(1, n_time);

options = optimset( ...
    'Display', 'off', ...
    'TolX', optimizer_tolerance);

%% ------------------------------------------------------------
% Fit models and generate held-out predictions
%% ------------------------------------------------------------

for held_out_fold = 1:n_time_folds


    test_time_indices = ...
        find(time_fold_id == held_out_fold);

    train_time_indices_all = ...
        find(time_fold_id ~= held_out_fold);

    train_time_indices = ...
        train_time_indices_all(1:fit_downsample:end);

    if isempty(train_time_indices)
        error('No training samples remain in fold %d.', held_out_fold);
    end

    y_train = ...
        deltaVmE(:, train_time_indices);

    inet_train = ...
        INetE(:, train_time_indices);

    %% --------------------------------------------------------
    % Model 1: fixed divisive gain
    %% --------------------------------------------------------

    objective_fixed = @(log_g0) ...
        fixed_divisive_model_sse( ...
            log_g0, ...
            y_train, ...
            inet_train);

    best_log_g0 = fminbnd( ...
        objective_fixed, ...
        log(beta_lower_bound), ...
        log(beta_upper_bound), ...
        options);

    fitted_g0 = exp(best_log_g0);

    fixed_prediction = ...
        INetE(:, test_time_indices) ./ (1 + fitted_g0);

    CV_fixed_gain_prediction(test_time_indices) = ...
        mean(fixed_prediction, 1);

    %% --------------------------------------------------------
    % Model 2: input-dependent divisive gain
    %% --------------------------------------------------------

    mean_ginput_train = ...
        mean(gInputE_history(:, train_time_indices), 1);

    positive_ginput = ...
        mean_ginput_train(mean_ginput_train > tiny);

    if isempty(positive_ginput)
        ginput_scale = 1;
    else
        ginput_scale = median(positive_ginput);
    end

    mean_ginput_scaled_train = ...
        mean_ginput_train ./ ginput_scale;

    objective_input = @(log_beta) ...
        explicit_gain_model_sse( ...
            log_beta, ...
            y_train, ...
            inet_train, ...
            mean_ginput_scaled_train);

    best_log_beta_input = fminbnd( ...
        objective_input, ...
        log(beta_lower_bound), ...
        log(beta_upper_bound), ...
        options);

    fitted_beta_input = ...
        exp(best_log_beta_input);

    mean_ginput_test = ...
        mean(gInputE_history(:, test_time_indices), 1);

    mean_ginput_scaled_test = ...
        mean_ginput_test ./ ginput_scale;

    input_denominator_test = ...
        1 + fitted_beta_input .* mean_ginput_scaled_test;

    input_prediction = ...
        INetE(:, test_time_indices) ./ input_denominator_test;

    CV_input_gain_prediction(test_time_indices) = ...
        mean(input_prediction, 1);

    %% --------------------------------------------------------
    % Model 3: inhibition-dependent divisive gain
    %% --------------------------------------------------------

    mean_ginh_train = ...
        mean(gInhE(:, train_time_indices), 1);

    positive_ginh = ...
        mean_ginh_train(mean_ginh_train > tiny);

    if isempty(positive_ginh)
        ginh_scale = 1;
    else
        ginh_scale = median(positive_ginh);
    end

    mean_ginh_scaled_train = ...
        mean_ginh_train ./ ginh_scale;

    objective_inhibitory = @(log_beta) ...
        explicit_gain_model_sse( ...
            log_beta, ...
            y_train, ...
            inet_train, ...
            mean_ginh_scaled_train);

    best_log_beta_inhibitory = fminbnd( ...
        objective_inhibitory, ...
        log(beta_lower_bound), ...
        log(beta_upper_bound), ...
        options);

    fitted_beta_inhibitory = ...
        exp(best_log_beta_inhibitory);

    mean_ginh_test = ...
        mean(gInhE(:, test_time_indices), 1);

    mean_ginh_scaled_test = ...
        mean_ginh_test ./ ginh_scale;

    inhibitory_denominator_test = ...
        1 + fitted_beta_inhibitory .* mean_ginh_scaled_test;

    inhibitory_prediction = ...
        INetE(:, test_time_indices) ./ inhibitory_denominator_test;

    CV_inhibitory_gain_prediction(test_time_indices) = ...
        mean(inhibitory_prediction, 1);

    %% --------------------------------------------------------
    % Comparison 1: fixed gain at mean inhibitory-model scale
    %% --------------------------------------------------------

    mean_inhibitory_denominator = ...
        mean( ...
            1 + fitted_beta_inhibitory .* mean_ginh_scaled_train);

    fixed_at_inhibitory_scale_prediction = ...
        INetE(:, test_time_indices) ./ ...
        mean_inhibitory_denominator;

    CV_fixed_at_inhibitory_scale_prediction(test_time_indices) = ...
        mean(fixed_at_inhibitory_scale_prediction, 1);

    %% --------------------------------------------------------
    % Comparison 2: input gain using inhibitory-model beta
    %% --------------------------------------------------------

    input_at_inhibitory_beta_denominator = ...
        1 + fitted_beta_inhibitory .* mean_ginput_scaled_test;

    input_at_inhibitory_beta_prediction = ...
        INetE(:, test_time_indices) ./ ...
        input_at_inhibitory_beta_denominator;

    CV_input_at_inhibitory_beta_prediction(test_time_indices) = ...
        mean(input_at_inhibitory_beta_prediction, 1);

end

%% ------------------------------------------------------------
% Verify complete held-out predictions
%% ------------------------------------------------------------

all_predictions = [ ...
    CV_fixed_gain_prediction; ...
    CV_input_gain_prediction; ...
    CV_inhibitory_gain_prediction; ...
    CV_fixed_at_inhibitory_scale_prediction; ...
    CV_input_at_inhibitory_beta_prediction];

if any(~isfinite(all_predictions), 'all')
    error('At least one model contains missing held-out predictions.');
end

%% ------------------------------------------------------------
% Assemble plotting arrays
%% ------------------------------------------------------------

actual_delta_v = ...
    population_observed_deltaVmE(:);

prediction_matrix = [ ...
    CV_fixed_gain_prediction(:), ...
    CV_input_gain_prediction(:), ...
    CV_inhibitory_gain_prediction(:)];

comparison_prediction_matrix = [ ...
    CV_fixed_at_inhibitory_scale_prediction(:), ...
    CV_input_at_inhibitory_beta_prediction(:)];

valid_samples = ...
    isfinite(actual_delta_v) & ...
    all(isfinite(prediction_matrix), 2) & ...
    all(isfinite(comparison_prediction_matrix), 2);

actual_delta_v = ...
    actual_delta_v(valid_samples);

prediction_matrix = ...
    prediction_matrix(valid_samples, :);

comparison_prediction_matrix = ...
    comparison_prediction_matrix(valid_samples, :);

if numel(actual_delta_v) < 3
    error('Too few valid population-average samples to plot.');
end

n_models_plot = ...
    size(prediction_matrix, 2);

%% ------------------------------------------------------------
% Compute least-squares slopes and intercepts
%% ------------------------------------------------------------

primary_fit_slope = ...
    nan(n_models_plot, 1);

primary_fit_intercept = ...
    nan(n_models_plot, 1);

for mm = 1:n_models_plot

    coefficients = polyfit( ...
        actual_delta_v, ...
        prediction_matrix(:, mm), ...
        1);

    primary_fit_slope(mm) = ...
        coefficients(1);

    primary_fit_intercept(mm) = ...
        coefficients(2);

end

comparison_fit_slope = ...
    nan(2, 1);

comparison_fit_intercept = ...
    nan(2, 1);

for mm = 1:2

    coefficients = polyfit( ...
        actual_delta_v, ...
        comparison_prediction_matrix(:, mm), ...
        1);

    comparison_fit_slope(mm) = ...
        coefficients(1);

    comparison_fit_intercept(mm) = ...
        coefficients(2);

end

%% ------------------------------------------------------------
% Shared plotting limits
%% ------------------------------------------------------------

all_plot_values = [ ...
    actual_delta_v; ...
    prediction_matrix(:); ...
    comparison_prediction_matrix(:)];

plot_min = min(all_plot_values);
plot_max = max(all_plot_values);
plot_range = plot_max - plot_min;

if ~isfinite(plot_range) || plot_range <= 0
    plot_range = max(abs(plot_min), 1);
end

plot_padding = 0.03 * plot_range;

shared_limits = [ ...
    plot_min - plot_padding, ...
    plot_max + plot_padding];

fit_x = linspace( ...
    shared_limits(1), ...
    shared_limits(2), ...
    500).';

%% ------------------------------------------------------------
% Create variables containing the five fitted lines
%
% Column 1 = x
% Column 2 = fitted y
%% ------------------------------------------------------------

fixed_gain_line = [ ...
    fit_x, ...
    primary_fit_intercept(1) + ...
    primary_fit_slope(1) .* fit_x];

input_gain_line = [ ...
    fit_x, ...
    primary_fit_intercept(2) + ...
    primary_fit_slope(2) .* fit_x];

inhibitory_gain_line = [ ...
    fit_x, ...
    primary_fit_intercept(3) + ...
    primary_fit_slope(3) .* fit_x];

fixed_at_inhibitory_scale_line = [ ...
    fit_x, ...
    comparison_fit_intercept(1) + ...
    comparison_fit_slope(1) .* fit_x];

input_at_inhibitory_beta_line = [ ...
    fit_x, ...
    comparison_fit_intercept(2) + ...
    comparison_fit_slope(2) .* fit_x];

%% ------------------------------------------------------------
% Put the five lines in one optional structure
%% ------------------------------------------------------------

fitted_lines = struct;

fitted_lines.fixed_gain = ...
    fixed_gain_line;

fitted_lines.input_gain = ...
    input_gain_line;

fitted_lines.inhibitory_gain = ...
    inhibitory_gain_line;

fitted_lines.fixed_at_inhibitory_scale = ...
    fixed_at_inhibitory_scale_line;

fitted_lines.input_at_inhibitory_beta = ...
    input_at_inhibitory_beta_line;

%% ------------------------------------------------------------
% Density-map settings
%% ------------------------------------------------------------

n_density_bins = 300;

x_edges = linspace( ...
    shared_limits(1), ...
    shared_limits(2), ...
    n_density_bins + 1);

y_edges = linspace( ...
    shared_limits(1), ...
    shared_limits(2), ...
    n_density_bins + 1);

x_centers = ...
    (x_edges(1:end-1) + x_edges(2:end)) ./ 2;

y_centers = ...
    (y_edges(1:end-1) + y_edges(2:end)) ./ 2;

%% ------------------------------------------------------------
% Organize line variables for plotting
%% ------------------------------------------------------------

primary_line_variables = { ...
    fixed_gain_line, ...
    input_gain_line, ...
    inhibitory_gain_line};

comparison_line_variables = { ...
    fixed_at_inhibitory_scale_line, ...
    input_at_inhibitory_beta_line};

%% ------------------------------------------------------------
% Plot
%% ------------------------------------------------------------

figure;

plot_layout = tiledlayout( ...
    1, ...
    n_models_plot, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

for mm = 1:n_models_plot

    ax = nexttile;
    hold(ax, 'on');

    this_prediction = ...
        prediction_matrix(:, mm);

    point_counts = histcounts2( ...
        actual_delta_v, ...
        this_prediction, ...
        x_edges, ...
        y_edges);

    log_point_density = ...
        log10(point_counts + 1);

    jitter_fraction = 0.003;
    jitter_sd = ...
        jitter_fraction * diff(shared_limits);

    x_plot = ...
        actual_delta_v + ...
        jitter_sd * randn(size(actual_delta_v));

    y_plot = ...
        this_prediction + ...
        jitter_sd * randn(size(this_prediction));

    scatter( ...
        ax, ...
        x_plot, ...
        y_plot, ...
        50, ...
        'k', ...
        'filled', ...
        'MarkerFaceAlpha', 0.009, ...
        'MarkerEdgeAlpha', 0.009);

    maximum_density = ...
        max(log_point_density, [], 'all');

    if maximum_density > 0
        clim(ax, [0 maximum_density]);
    else
        clim(ax, [0 1]);
    end

    % Identity line
    plot( ...
        ax, ...
        shared_limits, ...
        shared_limits, ...
        '--', ...
        'Color', [0 0 0], ...
        'LineWidth', 1.25);

    % Primary fitted line
    this_primary_line = ...
        primary_line_variables{mm};

    plot( ...
        ax, ...
        this_primary_line(:, 1), ...
        this_primary_line(:, 2), ...
        '-', ...
        'Color', [0 0 0], ...
        'LineWidth', 2);

    % Comparison fitted lines in panels 1 and 2
    if mm <= 2

        this_comparison_line = ...
            comparison_line_variables{mm};

        patch( ...
            ax, ...
            'XData', this_comparison_line(:, 1), ...
            'YData', this_comparison_line(:, 2), ...
            'FaceColor', 'none', ...
            'EdgeColor', [0 0 0], ...
            'EdgeAlpha', 0.30, ...
            'LineStyle', '-', ...
            'LineWidth', 2.5);

    end

    xlim(ax, [-20, 1]);
    ylim(ax, [-20, 1]);

    axis(ax, 'square');
    box(ax, 'off');

    xlabel( ...
        ax, ...
        'Actual population-average \DeltaV_m');

    if mm == 1
        ylabel( ...
            ax, ...
            'Predicted population-average \DeltaV_m');
    end

    title( ...
        ax, ...
        sprintf( ...
            'OLS Slope = %.3f', ...
            primary_fit_slope(mm)));

    set( ...
        ax, ...
        'FontName', 'Arial', ...
        'FontSize', 9, ...
        'LineWidth', 1, ...
        'TickDir', 'out', ...
        'XColor', [0 0 0], ...
        'YColor', [0 0 0]);

end

title( ...
    plot_layout, ...
    'Population-average actual versus predicted voltage changes');

%% ============================================================
% Local functions
%% ============================================================

function matrix = orient_cells_by_time( ...
        matrix, n_time, variable_name)

    if size(matrix, 2) == n_time
        return
    end

    if size(matrix, 1) == n_time
        matrix = matrix.';
        return
    end

    error( ...
        ['Variable "%s" has dimensions %d x %d, and neither ' ...
         'dimension matches the %d time samples.'], ...
        variable_name, ...
        size(matrix, 1), ...
        size(matrix, 2), ...
        n_time);

end

function sse = fixed_divisive_model_sse( ...
        log_g0, observed_delta_v, inet)

    g0 = exp(log_g0);

    predicted_delta_v = ...
        inet ./ (1 + g0);

    residual = ...
        observed_delta_v - predicted_delta_v;

    sse = ...
        sum(residual.^2, 'all');

    if ~isfinite(sse)
        sse = realmax('double');
    end

end

function sse = explicit_gain_model_sse( ...
        log_beta, observed_delta_v, inet, mean_g_scaled)

    beta = exp(log_beta);

    denominator = ...
        1 + beta .* mean_g_scaled;

    predicted_delta_v = ...
        inet ./ denominator;

    residual = ...
        observed_delta_v - predicted_delta_v;

    sse = ...
        sum(residual.^2, 'all');

    if ~isfinite(sse)
        sse = realmax('double');
    end

end